name: Update counters

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update-counters:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    # --------------------------
    - name: Cache OpenAF runtime
      uses: actions/cache@v4
      with:
        key : oaf-nightly
        path: /tmp/oaf  

    # -------------------------
    - uses: actions/checkout@v4

    # ---------------------
    - name: Update counters
      uses: openaf/ojob-action@v7
      with:
        dist: nightly
        ojob: .github/ojobs/updateCounters.yaml
    
    # --------------------
    - name: Commit changes
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: openaf/ojob-action@v7
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="Update\ counters" paths=".github/"'
        dist: nightly
